export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const USER_UPLOAD_AVATAR = "USER_UPLOAD_AVATAR";
// export const USER_PROFILE = "USER_PROFILE";